---
title: "ALS"
author: "Stanisław Wilczyński, Mikołaj Dzięciołowski, Dominik Samorek, Michał Stypułkowski"
date: "23 grudnia 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(coda)
require(ggmcmc)
require(runjags)
require(lattice)
require(BBmisc)
require(R2jags)
require(superdiag)
set.seed(42)


ALS <- read.table('./../../datasets/ALS.txt',header=T)

#create new ids
ALS <- transform(ALS, subject_id=as.numeric(factor(subject_id)))
```

Models
```{r}
cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 + b.rand[subject_id[i], 1] + (b1 + b.rand[subject_id[i], 2]) * time[i]  
  }

  for (i in 1:M) {
    b.rand[i, 1:2] ~ dmnorm(b.rand.mean[1:2], b.rand.tau[1:2,1:2])
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)
  
  # random effects
  b.rand.tau ~ dwish(b.R[1:2,1:2], 2)
  
  b.rand.sigma2[1:2,1:2]  <- inverse(b.rand.tau[1:2,1:2])
  for (i in 1:2) {
    b.rand.sigma[i] <- sqrt(b.rand.sigma2[i,i])
  }
  b.rand.corr <- b.rand.sigma2[1,2]/(b.rand.sigma[1]*b.rand.sigma[2])
  
  b.rand.int.means <- mean(b.rand[,1])
  b.rand.slp.means <- mean(b.rand[,2])
}", file="./jags_files/als.model")

cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 + b.rand[subject_id[i], 1] + (b1 + b.rand[subject_id[i], 2]) * time[i]  
  }

  for (i in 1:M) {
    b.rand[i, 1:2] ~ dmnorm(b.rand.mean[1:2], b.rand.tau[1:2,1:2])
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-3)
  b1 ~ dnorm(0, 1.0E-3)
  
  # random effects
  b.rand.tau ~ dwish(b.R[1:2,1:2], 2)
  
  b.rand.sigma2[1:2,1:2]  <- inverse(b.rand.tau[1:2,1:2])
  for (i in 1:2) {
    b.rand.sigma[i] <- sqrt(b.rand.sigma2[i,i])
  }
  b.rand.corr <- b.rand.sigma2[1,2]/(b.rand.sigma[1]*b.rand.sigma[2])
  
  b.rand.int.means <- mean(b.rand[,1])
  b.rand.slp.means <- mean(b.rand[,2])
}", file="./jags_files/als.model.small.sigma")

cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 + b.rand[subject_id[i], 1] + (b1 + b.rand[subject_id[i], 2]) * time[i]  
  }

  for (i in 1:M) {
    b.rand[i, 1:2] ~ dmnorm(b.rand.mean[1:2], b.rand.tau[1:2,1:2])
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)
  
  # random effects
  b.rand.taui[1,1] <- pow(b.rand.sigma[1],2)
  b.rand.taui[1,2] <- b.rand.corr * b.rand.sigma[1] * b.rand.sigma[2]
  b.rand.taui[2,1] <- b.rand.corr * b.rand.sigma[1] * b.rand.sigma[2]
  b.rand.taui[2,2] <- pow(b.rand.sigma[2], 2)
  b.rand.tau <- inverse(b.rand.taui[1:2, 1:2])
  
  b.rand.sigma[1] ~ dunif(0, 100)
  b.rand.sigma[2] ~ dunif(0, 100)
  b.rand.corr ~ dunif(-1, 1)
  
  b.rand.int.means <- mean(b.rand[,1])
  b.rand.slp.means <- mean(b.rand[,2])
}", file="./jags_files/als.model.unif")

cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 + b.rand[subject_id[i], 1] + (b1 + b.rand[subject_id[i], 2]) * time[i]  
  }

  for (i in 1:M) {
    b.rand[i, 1] ~ dnorm(0, pow(b.rand.sigma[1], -2))
    b.rand[i, 2] ~ dnorm(0, pow(b.rand.sigma[2], -2))
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)
  
  # random effects
  b.rand.sigma[1] ~ dunif(0, 100)
  b.rand.sigma[2] ~ dunif(0, 100)
  
  b.rand.int.means <- mean(b.rand[,1])
  b.rand.slp.means <- mean(b.rand[,2])
}", file="./jags_files/als.model.independent")

cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 + b.rand[subject_id[i], 1] + (b1 + b.rand[subject_id[i], 2]) * time[i]  
  }

  for (i in 1:M) {
    b.rand[i, 1] ~ dnorm(0, pow(b.rand.sigma, -2))
    b.rand[i, 2] ~ dnorm(0, pow(b.rand.sigma, -2))
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)
  
  # random effects
  b.rand.sigma ~ dunif(0, 100)
  
  b.rand.int.means <- mean(b.rand[,1])
  b.rand.slp.means <- mean(b.rand[,2])
}", file="./jags_files/als.model.diagonal")

cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 + b.rand[subject_id[i]] + b1 * time[i]  
  }

  for (i in 1:M) {
    b.rand[i] ~ dnorm(0, pow(b.rand.sigma, -2))
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)
  
  # random effects
  b.rand.sigma ~ dunif(0, 100)

}", file="./jags_files/als.model.int")

cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 + (b.rand[subject_id[i]] + b1) * time[i]  
  }

  for (i in 1:M) {
    b.rand[i] ~ dnorm(0, pow(b.rand.sigma, -2))
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)
  
  # random effects
  b.rand.sigma ~ dunif(0, 100)

}", file="./jags_files/als.model.slp")

cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 +  b1 * time[i]  
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)

}", file="./jags_files/als.model.norand")

```


```{r}
als.data <- list(
  bin.score = ALS$bin_score,
  time = ALS$time,
  subject_id = ALS$subject_id,
  N = nrow(ALS),
  b.rand.mean = c(0, 0),
  b.R = diag(0.1, 2),
  M = length(unique(ALS$subject_id))
)
als.inits = list(
  list(
    b0=0.5,
    b1=-8,
    b.rand.tau=structure(
    .Data=c(0.2, 0.0,0.0, 0.2),
    .Dim=c(2,2))
  ),
  list(
    b0=0.4,
    b1=-7,
    b.rand.tau=structure(
    .Data=c(0.1, 0.0,0.0, 0.1),
    .Dim=c(2,2))
  ),
  list(
    b0=0.6,
    b1=-9,
    b.rand.tau=structure(
    .Data=c(0.3, 0.0,0.0, 0.3),
    .Dim=c(2,2))
  )
)
```

```{r}
test.model <- function(iterations, model.file, monitor=c("b0", "b1", "b.rand.sigma", "b.rand.corr"), data=als.data, inits=als.inits, thin=1) {
  als.model.jags <- jags(model.file = model.file, data = data, parameters.to.save = monitor, n.chains = 3, inits = inits, n.burnin = iterations/2, n.iter = iterations, n.thin = thin, DIC=T)
 als.model.jags
}


test.model.runjags <- function(iterations, model.file, monitor=c("b0", "b1", "b.rand.sigma", "b.rand.corr", "dic", "pD", "deviance"), data=als.data, inits=als.inits) {
 als.model.jags <- run.jags(model = model.file, data = dump.format(data), monitor = monitor, n.chains = 3, inits = inits, burnin = iterations/2, sample = iterations, keep.jags.files = F, method = "parallel")
 als.model.jags
}
summarise.model <- function(model, plots.file, iterations) {
  als.model.mcmc <- as.mcmc(model)
  als.model.gg <- ggs(als.model.mcmc)
  #summary(model)
  ggmcmc(als.model.gg, plots.file)
}

summarise.model.runjags <- function(model, plots.file, iterations) {
  als.model.mcmc <- as.mcmc.list(model)
  als.model.gg <- ggs(als.model.mcmc)
  #summary(model)
  ggmcmc(als.model.gg, plots.file)
}
```

```{r}
iters=40000
als.model <- test.model(iters, "./jags_files/als.model")
summarise.model(als.model, "./../als_model_plot.pdf", iters)
```
```{r}
als.small.model <- test.model(iters, "./jags_files/als.model.small.sigma")
summarise.model(als.small.model, "./../als_model_small_sigma_plot.pdf", iters)
```
```{r}
als.unif.data <- list(
  bin.score = ALS$bin_score,
  time = ALS$time,
  subject_id = ALS$subject_id,
  N = nrow(ALS),
  b.rand.mean = c(0, 0),
  M = length(unique(ALS$subject_id))
)
als.unif.inits = list(
  list(
    b0=0.5,
    b1=-8,
    b.rand.sigma = c(6,6),
    b.rand.corr = 0.3
  ),
  list(
    b0=0.4,
    b1=-7,
    b.rand.sigma = c(7,7),
    b.rand.corr = 0.4
  ),
  list(
    b0=0.6,
    b1=-9,
    b.rand.sigma = c(8,8),
    b.rand.corr = 0.5
  )
)
als.unif.model <- test.model(iters, "./jags_files/als.model.unif", data=als.unif.data, inits=als.unif.inits)
summarise.model(als.unif.model, "./../als_model_unif.pdf", iters)
```


```{r}
als.ind.data <- list(
  bin.score = ALS$bin_score,
  time = ALS$time,
  subject_id = ALS$subject_id,
  N = nrow(ALS),
  M = length(unique(ALS$subject_id))
)
als.ind.inits = list(
  list(
    b0=0.5,
    b1=-8,
    b.rand.sigma = c(6,6)
  ),
  list(
    b0=0.4,
    b1=-7,
    b.rand.sigma = c(7,7)
  ),
  list(
    b0=0.6,
    b1=-9,
    b.rand.sigma = c(8,8)
  )
)
als.ind.model <- test.model(iters, "./jags_files/als.model.independent", data=als.ind.data, inits=als.ind.inits, monitor = c("b0", "b1", "b.rand.sigma"))
summarise.model(als.ind.model, "./../als_model_ind.pdf", iters)
```

```{r}
als.diag.inits = list(
  list(
    b0=0.5,
    b1=-8,
    b.rand.sigma = 6
  ),
  list(
    b0=0.4,
    b1=-7,
    b.rand.sigma = 7
  ),
  list(
    b0=0.6,
    b1=-9,
    b.rand.sigma = 8
  )
)
als.diag.model <- test.model(iters, "./jags_files/als.model.diagonal", data=als.ind.data, inits=als.diag.inits, monitor = c("b0", "b1", "b.rand.sigma"))
summarise.model(als.diag.model, "./../als_model_diag.pdf", iters)
```

```{r}
als.int.model <- test.model(iters, "./jags_files/als.model.int", data=als.ind.data, inits=als.diag.inits, monitor = c("b0", "b1", "b.rand.sigma"))
summarise.model(als.int.model, "./../als_model_int.pdf", iters)
```


```{r}
als.slp.model <- test.model(iters, "./jags_files/als.model.slp", data=als.ind.data, inits=als.diag.inits, monitor = c("b0", "b1", "b.rand.sigma"))
summarise.model(als.slp.model, "./../als_model_slp.pdf", iters)
```

```{r}
als.norand.inits = list(
  list(
    b0=0.5,
    b1=-8
  ),
  list(
    b0=0.4,
    b1=-7
  ),
  list(
    b0=0.6,
    b1=-9
  )
)
als.norand.model <- test.model(iters, "./jags_files/als.model.norand", data=als.ind.data, inits=als.norand.inits, monitor = c("b0", "b1"))
summarise.model(als.norand.model, "./../als_model_norand.pdf", iters)
```
DIC
```{r}
models.jags <- list(als.model, als.small.model, als.unif.model, als.ind.model, als.diag.model, als.slp.model, als.int.model, als.norand.model)
models.mcmc <- lapply(models.jags, as.mcmc)
models.ggs <- lapply(models.mcmc, ggs)
getDIC <- function(model) {
  model$BUGSoutput$DIC
}
DICs <- lapply(models.jags, getDIC)
```
```{r}
DICs[[5]]
gelman.diag(models.mcmc[[5]])
```
Additional tests
```{r}
als.data.wish <- list(
  bin.score = ALS$bin_score,
  time = ALS$time,
  subject_id = ALS$subject_id,
  N = nrow(ALS),
  b.rand.mean = c(0, 0),
  b.R = diag(0.01, 2),
  M = length(unique(ALS$subject_id))
)
cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b0 + b.rand[subject_id[i], 1] + (b1 + b.rand[subject_id[i], 2]) * time[i]  
  }

  for (i in 1:M) {
    b.rand[i, 1:2] ~ dmnorm(b.rand.mean[1:2], b.rand.tau[1:2,1:2])
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)
  
  # random effects
  b.rand.taui[1,1] <- pow(b.rand.sigma[1],2)
  b.rand.taui[1,2] <- b.rand.corr * b.rand.sigma[1] * b.rand.sigma[2]
  b.rand.taui[2,1] <- b.rand.corr * b.rand.sigma[1] * b.rand.sigma[2]
  b.rand.taui[2,2] <- pow(b.rand.sigma[2], 2)
  b.rand.tau <- inverse(b.rand.taui[1:2, 1:2])
  
  b.rand.sigma[1] ~ dunif(0, 100000)
  b.rand.sigma[2] ~ dunif(0, 100000)
  b.rand.corr ~ dunif(-1, 1)
  
  b.rand.int.means <- mean(b.rand[,1])
  b.rand.slp.means <- mean(b.rand[,2])
}", file="./jags_files/als.model.unif.big")

cat("model {
  for(i in 1:N){
    bin.score[i] ~ dbern(p[i])
    logit(p[i]) <- b.rand[subject_id[i], 1] + b.rand[subject_id[i], 2] * time[i]  
  }

  for (i in 1:M) {
    b.rand[i, 1] ~ dnorm(b0, pow(b.rand.sigma, -2))
    b.rand[i, 2] ~ dnorm(b1, pow(b.rand.sigma, -2))
  }

  # fixed effects
  b0 ~ dnorm(0, 1.0E-6)
  b1 ~ dnorm(0, 1.0E-6)
  
  # random effects
  b.rand.sigma ~ dunif(0, 100)
  
  b.rand.int.means <- mean(b.rand[,1])
  b.rand.slp.means <- mean(b.rand[,2])
}", file="./jags_files/als.model.diagonal.cent")

als.wish.model <- test.model(iters, "./jags_files/als.model", data=als.data.wish)
summarise.model(als.wish.model, "./../als_model_wish.pdf", iters)

als.unif.big.model <- test.model(iters, "./jags_files/als.model.unif.big", data=als.unif.data, inits=als.unif.inits)
summarise.model(als.unif.big.model, "./../als_model_unif_big.pdf", iters)

als.diag.thin.model <- test.model(iters, "./jags_files/als.model.diagonal", data=als.ind.data, inits=als.diag.inits, monitor = c("b0", "b1", "b.rand.sigma"), thin = 10)
summarise.model(als.diag.thin.model, "./../als_model_diag_thin.pdf", iters)

als.diag.centered.model <- test.model(iters, "./jags_files/als.model.diagonal.cent", data=als.ind.data, inits=als.diag.inits, monitor = c("b0", "b1", "b.rand.sigma"))
summarise.model(als.diag.centered.model, "./../als_model_diag_centered.pdf", iters)

```
```{r}
print(summary(as.mcmc(als.unif.big.model))$statistics)
print(summary(as.mcmc(als.unif.model))$statistics)
print(summary(as.mcmc(als.model))$statistics)
print(summary(as.mcmc(als.wish.model))$statistics)
print(summary(as.mcmc(als.small.model))$statistics)
print(summary(as.mcmc(als.diag.model))$statistics)

```


```{r}
#traceplot
ggs_traceplot(als.model.gg)
#autocorrelation plo
ggs_autocorrelation(als.model.gg)+theme_classic()
#running mean
ggs_running(als.model.gg) + theme_classic()
#cross-correlation plot
ggs_crosscorrelation(als.model.gg) + theme_classic()
#geweke diagnostic
ggs_geweke(als.model.gg,frac1=0.1,frac2=0.5) + theme_classic()
#BGR diagnostics version 1(R_c)
ggs_Rhat(als.model.gg)+ theme_classic()
#BGR diagnostic version 2
gelman.plot(als.model.mcmc)
#time series approach to estimating monte carlo standard error(MCSE)
summary(als.model.mcmc)
#effective sample size
effectiveSize(als.model.mcmc)
```




